<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>CapsLockSharp</AssemblyName>
    <RootNamespace>CapsLockSharp</RootNamespace>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

</Project>
